"""admin units and map views

Revision ID: 6ded04ecf24f
Revises: b8cb186ad277
Create Date: 2026-09-26 14:21:50.880588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ded04ecf24f'
down_revision: Union[str, Sequence[str], None] = 'b8cb186ad277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Local time (America/Guayaquil) is required for year/month: Ecuador has no
# DST, but UTC still shifts New Year's Eve incidents into the wrong year.
_MAP_INCIDENTS_VIEW = """
CREATE VIEW map_incidents AS
SELECT
    id,
    type,
    confidence,
    geom,
    EXTRACT(YEAR FROM occurred_at AT TIME ZONE 'America/Guayaquil')::integer AS year,
    EXTRACT(MONTH FROM occurred_at AT TIME ZONE 'America/Guayaquil')::integer AS month,
    province_code,
    canton_code
FROM incidents
WHERE status = 'activo'
  AND located_at IS NULL
  AND location_precision <> 'canton'
  AND EXTRACT(YEAR FROM occurred_at AT TIME ZONE 'America/Guayaquil') >= 2019
"""

_MAP_DETENTIONS_VIEW = """
CREATE VIEW map_detentions AS
SELECT
    id,
    geom,
    EXTRACT(YEAR FROM occurred_at AT TIME ZONE 'America/Guayaquil')::integer AS year,
    EXTRACT(MONTH FROM occurred_at AT TIME ZONE 'America/Guayaquil')::integer AS month,
    province_code,
    canton_code,
    detention_type
FROM detentions
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_units',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('level', sa.Enum('province', 'canton', name='admin_unit_level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['province_code'], ['admin_units.code'], name=op.f('fk_admin_units_province_code_admin_units')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_admin_units'))
    )
    # ### end Alembic commands ###

    # Hand-written: the two read-only views Martin publishes as tile sources
    # and the API queries -- never autogenerated, and Base.metadata never
    # declares them (see app/database/views.py), so Alembic never proposes
    # dropping them either.
    op.execute(_MAP_INCIDENTS_VIEW)
    op.execute(_MAP_DETENTIONS_VIEW)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS map_detentions")
    op.execute("DROP VIEW IF EXISTS map_incidents")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_units')
    # ### end Alembic commands ###
