"""canton indicators and map cantons view

Revision ID: 92eafee9aa9d
Revises: 7c4625d66b31
Create Date: 2026-09-26 16:46:23.767793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92eafee9aa9d'
down_revision: Union[str, Sequence[str], None] = '7c4625d66b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Canton polygons at national-choropleth zoom levels don't need full detail;
# 0.002 degrees (~200m at the equator) keeps `map_cantons` tiles small while
# staying visually indistinguishable from the source boundary at the zoom
# levels the frontend renders it (a national/provincial overview, not a
# street-level view) -- checked by eye against a few coastal/Amazon cantons
# whose boundaries are the most detailed (many small bends).
_SIMPLIFY_TOLERANCE = 0.002

_MAP_CANTONS_VIEW = f"""
CREATE VIEW map_cantons AS
SELECT
    code,
    name,
    province_code,
    ST_SimplifyPreserveTopology(geom, {_SIMPLIFY_TOLERANCE}) AS geom
FROM cantons
WHERE code IS NOT NULL
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canton_indicators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indicator', sa.Enum('extorsion', 'secuestro_extorsivo', 'siniestros', 'siniestros_fallecidos', name='canton_indicator', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('canton_code', sa.String(length=4), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_canton_indicators_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canton_indicators')),
    sa.UniqueConstraint('indicator', 'canton_code', 'year', 'month', name=op.f('uq_canton_indicators_indicator_canton_code_year_month'))
    )
    op.create_index('ix_canton_indicators_indicator_year', 'canton_indicators', ['indicator', 'year'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: the third read-only view Martin publishes as a tile
    # source and the API queries -- never autogenerated, and Base.metadata
    # never declares it (see app/database/views.py), so Alembic never
    # proposes dropping it either. The first polygon layer (map_incidents/
    # map_detentions are points).
    op.execute(_MAP_CANTONS_VIEW)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS map_cantons")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_canton_indicators_indicator_year', table_name='canton_indicators')
    op.drop_table('canton_indicators')
    # ### end Alembic commands ###
