"""initial schema

Revision ID: b8cb186ad277
Revises: 
Create Date: 2026-09-26 00:27:06.108145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'b8cb186ad277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fresh databases (production) may not have PostGIS enabled yet.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_geospatial_table('detentions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('detention_type', sa.Enum('detenido', 'aprehendido', name='detention_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('iccs_code', sa.String(length=16), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=True),
    sa.Column('canton_code', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_detentions_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detentions')),
    sa.UniqueConstraint('source_id', 'source_record_id', name=op.f('uq_detentions_source_id_source_record_id'))
    )
    op.create_geospatial_index('idx_detentions_geom', 'detentions', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_detentions_canton_code'), 'detentions', ['canton_code'], unique=False)
    op.create_index(op.f('ix_detentions_occurred_at'), 'detentions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_detentions_province_code'), 'detentions', ['province_code'], unique=False)
    op.create_geospatial_table('incidents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('homicidio', 'sicariato', 'femicidio', 'desaparecida', 'siniestro_transito', 'tiroteo', 'robo', 'secuestro', 'extorsion', 'violencia_sexual', 'rina', 'otro', name='incident_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Enum('oficial', 'verificado', 'reportado', 'en_revision', name='confidence', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('activo', 'retirado', 'fusionado', name='incident_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('merged_into_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location_precision', sa.Enum('exacta', 'aproximada', 'canton', name='location_precision', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=True),
    sa.Column('canton_code', sa.String(length=4), nullable=True),
    sa.Column('located_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['incidents.id'], name=op.f('fk_incidents_merged_into_id_incidents')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_incidents_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('source_id', 'source_record_id', name=op.f('uq_incidents_source_id_source_record_id'))
    )
    op.create_geospatial_index('idx_incidents_geom', 'incidents', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_incidents_canton_code'), 'incidents', ['canton_code'], unique=False)
    op.create_index(op.f('ix_incidents_occurred_at'), 'incidents', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_incidents_province_code'), 'incidents', ['province_code'], unique=False)
    op.create_index(op.f('ix_incidents_type'), 'incidents', ['type'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='run_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_pipeline_runs_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index(op.f('ix_pipeline_runs_file_hash'), 'pipeline_runs', ['file_hash'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_source_id'), 'pipeline_runs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_source_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_file_hash'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_incidents_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_province_code'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_occurred_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_canton_code'), table_name='incidents')
    op.drop_geospatial_index('idx_incidents_geom', table_name='incidents', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('incidents')
    op.drop_index(op.f('ix_detentions_province_code'), table_name='detentions')
    op.drop_index(op.f('ix_detentions_occurred_at'), table_name='detentions')
    op.drop_index(op.f('ix_detentions_canton_code'), table_name='detentions')
    op.drop_geospatial_index('idx_detentions_geom', table_name='detentions', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('detentions')
    op.drop_table('sources')
    # ### end Alembic commands ###
