"""cantons and population

Revision ID: 7c4625d66b31
Revises: 6ded04ecf24f
Create Date: 2026-09-26 15:38:03.669252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '7c4625d66b31'
down_revision: Union[str, Sequence[str], None] = '6ded04ecf24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canton_population',
    sa.Column('canton_code', sa.String(length=4), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('canton_code', 'year', name=op.f('pk_canton_population'))
    )
    op.create_geospatial_table('cantons',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_cantons'))
    )
    op.create_geospatial_index('idx_cantons_centroid', 'cantons', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_cantons_geom', 'cantons', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_cantons_province_code'), 'cantons', ['province_code'], unique=False)
    op.create_index(op.f('ix_incidents_merged_into_id'), 'incidents', ['merged_into_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_merged_into_id'), table_name='incidents')
    op.drop_index(op.f('ix_cantons_province_code'), table_name='cantons')
    op.drop_geospatial_index('idx_cantons_geom', table_name='cantons', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_index('idx_cantons_centroid', table_name='cantons', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_table('cantons')
    op.drop_table('canton_population')
    # ### end Alembic commands ###
